# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default='tess', max_length=50),
            preserve_default=False,
        ),
    ]
