# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_and_registration', '0002_user_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distiller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_distiller', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bev_reviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beverages.Beverage')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_and_registration.User')),
            ],
        ),
        migrations.AddField(
            model_name='beverage',
            name='distiller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beverages.Distiller'),
        ),
    ]
