# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distiller',
            name='distiller_details',
            field=models.TextField(default='details go here', max_length=1000),
        ),
    ]
