# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_registration', '0002_user_alias'),
        ('beverages', '0002_distiller_distiller_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Try',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tried', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('try_beverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beverages.Beverage')),
                ('try_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_and_registration.User')),
            ],
        ),
    ]
