# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0004_auto_20170103_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorpoint',
            name='favor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favor_user', to='login_and_registration.User'),
        ),
    ]
