# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beverages', '0005_auto_20170104_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverage',
            name='favor_total',
            field=models.IntegerField(default=0),
        ),
    ]
